include:
  project: gardenlinux/gardenlinux-package-build
  file: pipeline/pipeline.yml

variables:
  SOURCE_NAME: systemd
  SOURCE_DIST: experimental
  DEB_BUILD_OPTIONS: nocheck noudeb terse
  DEB_BUILD_PROFILES: nocheck noudeb
  BUILD_ARCH_ALL: 'true'
